package com.campray.lesswalletmerchant.db.dao;

import java.util.List;
import java.util.ArrayList;
import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.SqlUtils;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.campray.lesswalletmerchant.db.entity.Currency;

import com.campray.lesswalletmerchant.db.entity.Language;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "LANGUAGE".
*/
public class LanguageDao extends AbstractDao<Language, Long> {

    public static final String TABLENAME = "LANGUAGE";

    /**
     * Properties of entity Language.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property Name = new Property(1, String.class, "name", false, "NAME");
        public final static Property LanguageCulture = new Property(2, String.class, "languageCulture", false, "LANGUAGE_CULTURE");
        public final static Property UniqueSeoCode = new Property(3, String.class, "uniqueSeoCode", false, "UNIQUE_SEO_CODE");
        public final static Property DisplayOrder = new Property(4, int.class, "displayOrder", false, "DISPLAY_ORDER");
        public final static Property DefaultCurrencyId = new Property(5, Long.class, "defaultCurrencyId", false, "DEFAULT_CURRENCY_ID");
    }

    private DaoSession daoSession;


    public LanguageDao(DaoConfig config) {
        super(config);
    }
    
    public LanguageDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
        this.daoSession = daoSession;
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"LANGUAGE\" (" + //
                "\"_id\" INTEGER PRIMARY KEY ," + // 0: id
                "\"NAME\" TEXT NOT NULL ," + // 1: name
                "\"LANGUAGE_CULTURE\" TEXT NOT NULL ," + // 2: languageCulture
                "\"UNIQUE_SEO_CODE\" TEXT NOT NULL ," + // 3: uniqueSeoCode
                "\"DISPLAY_ORDER\" INTEGER NOT NULL ," + // 4: displayOrder
                "\"DEFAULT_CURRENCY_ID\" INTEGER NOT NULL );"); // 5: defaultCurrencyId
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"LANGUAGE\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, Language entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindString(2, entity.getName());
        stmt.bindString(3, entity.getLanguageCulture());
        stmt.bindString(4, entity.getUniqueSeoCode());
        stmt.bindLong(5, entity.getDisplayOrder());
        stmt.bindLong(6, entity.getDefaultCurrencyId());
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, Language entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindString(2, entity.getName());
        stmt.bindString(3, entity.getLanguageCulture());
        stmt.bindString(4, entity.getUniqueSeoCode());
        stmt.bindLong(5, entity.getDisplayOrder());
        stmt.bindLong(6, entity.getDefaultCurrencyId());
    }

    @Override
    protected final void attachEntity(Language entity) {
        super.attachEntity(entity);
        entity.__setDaoSession(daoSession);
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public Language readEntity(Cursor cursor, int offset) {
        Language entity = new Language( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.getString(offset + 1), // name
            cursor.getString(offset + 2), // languageCulture
            cursor.getString(offset + 3), // uniqueSeoCode
            cursor.getInt(offset + 4), // displayOrder
            cursor.getLong(offset + 5) // defaultCurrencyId
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, Language entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setName(cursor.getString(offset + 1));
        entity.setLanguageCulture(cursor.getString(offset + 2));
        entity.setUniqueSeoCode(cursor.getString(offset + 3));
        entity.setDisplayOrder(cursor.getInt(offset + 4));
        entity.setDefaultCurrencyId(cursor.getLong(offset + 5));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(Language entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(Language entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(Language entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
    private String selectDeep;

    protected String getSelectDeep() {
        if (selectDeep == null) {
            StringBuilder builder = new StringBuilder("SELECT ");
            SqlUtils.appendColumns(builder, "T", getAllColumns());
            builder.append(',');
            SqlUtils.appendColumns(builder, "T0", daoSession.getCurrencyDao().getAllColumns());
            builder.append(" FROM LANGUAGE T");
            builder.append(" LEFT JOIN CURRENCY T0 ON T.\"DEFAULT_CURRENCY_ID\"=T0.\"_id\"");
            builder.append(' ');
            selectDeep = builder.toString();
        }
        return selectDeep;
    }
    
    protected Language loadCurrentDeep(Cursor cursor, boolean lock) {
        Language entity = loadCurrent(cursor, 0, lock);
        int offset = getAllColumns().length;

        Currency currency = loadCurrentOther(daoSession.getCurrencyDao(), cursor, offset);
         if(currency != null) {
            entity.setCurrency(currency);
        }

        return entity;    
    }

    public Language loadDeep(Long key) {
        assertSinglePk();
        if (key == null) {
            return null;
        }

        StringBuilder builder = new StringBuilder(getSelectDeep());
        builder.append("WHERE ");
        SqlUtils.appendColumnsEqValue(builder, "T", getPkColumns());
        String sql = builder.toString();
        
        String[] keyArray = new String[] { key.toString() };
        Cursor cursor = db.rawQuery(sql, keyArray);
        
        try {
            boolean available = cursor.moveToFirst();
            if (!available) {
                return null;
            } else if (!cursor.isLast()) {
                throw new IllegalStateException("Expected unique result, but count was " + cursor.getCount());
            }
            return loadCurrentDeep(cursor, true);
        } finally {
            cursor.close();
        }
    }
    
    /** Reads all available rows from the given cursor and returns a list of new ImageTO objects. */
    public List<Language> loadAllDeepFromCursor(Cursor cursor) {
        int count = cursor.getCount();
        List<Language> list = new ArrayList<Language>(count);
        
        if (cursor.moveToFirst()) {
            if (identityScope != null) {
                identityScope.lock();
                identityScope.reserveRoom(count);
            }
            try {
                do {
                    list.add(loadCurrentDeep(cursor, false));
                } while (cursor.moveToNext());
            } finally {
                if (identityScope != null) {
                    identityScope.unlock();
                }
            }
        }
        return list;
    }
    
    protected List<Language> loadDeepAllAndCloseCursor(Cursor cursor) {
        try {
            return loadAllDeepFromCursor(cursor);
        } finally {
            cursor.close();
        }
    }
    

    /** A raw-style query where you can pass any WHERE clause and arguments. */
    public List<Language> queryDeep(String where, String... selectionArg) {
        Cursor cursor = db.rawQuery(getSelectDeep() + where, selectionArg);
        return loadDeepAllAndCloseCursor(cursor);
    }
 
}
